// import "./globals.css";
// import { ClusterProvider } from "@/components/cluster/cluster-data-access";
// import { SolanaProvider } from "@/components/solana/solana-provider";
// import { UiLayout } from "@/components/ui/ui-layout";
// import { ReactQueryProvider } from "./react-query-provider";

// export const metadata = {
//   title: "template-next-tailwind-counter",
//   description: "Generated by create-solana-dapp",
// };

// const links: { label: string; path: string }[] = [
//   { label: "Account", path: "/account" },
//   { label: "Clusters", path: "/clusters" },
// ];

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <ReactQueryProvider>
//           <ClusterProvider>
//             <SolanaProvider>
//               <UiLayout links={links}>{children}</UiLayout>
//             </SolanaProvider>
//           </ClusterProvider>
//         </ReactQueryProvider>
//       </body>
//     </html>
//   );
// }

// 2.0
// File: /app/layout.tsx
// import "./globals.css";
// import { AppProviders } from "@/contexts/AppProviders";
// import { UiLayout } from "@/components/ui/ui-layout";

// const links: { label: string; path: string }[] = [
//   { label: "Account", path: "/account" },
//   { label: "Clusters", path: "/clusters" },
// ];

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <AppProviders>
//           <UiLayout links={links}>{children}</UiLayout>
//         </AppProviders>
//       </body>
//     </html>
//   );
// }

//3.0
// File: /app/layout.tsx
import "./globals.css";
import { ClientProviders } from "@/components/providers/ClientProviders";
import { UiLayout } from "@/components/ui/ui-layout";

const links = [
  { label: "Account", path: "/account" },
  { label: "Clusters", path: "/clusters" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          <UiLayout links={links}>{children}</UiLayout>
        </ClientProviders>
      </body>
    </html>
  );
}
